version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - bundle install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby on Rails application...
      - bundle exec rake assets:precompile
  post_build:
    commands:
      - echo Build completed on `date`