version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.0.1
    commands:
      - echo "Installing dependencies"
      - gem install bundler
      - bundle install

  pre_build:
    commands:
      - echo "Running pre-build"
      - bundle exec rake db:create db:migrate

  build:
    commands:
      - echo "Running tests"
      - bundle exec rspec

artifacts:
  files:
    - Gemfile.lock
    - public/**/*
    # Add any other files or directories you want to include in the build artifact