version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
    commands:
      - echo "Installing dependencies"
      - rbenv global 3.2.2
      - gem install bundler
      - bundle install

  build:
    commands:
      - echo "Running tests"
      # - bundle exec rspec

artifacts:
  files:
    - Gemfile.lock
    - public/**/*
    # Add any other files or directories you want to include in the build artifact
